name: Container Pipeline Test

on: push

jobs:
  build:
    name: Build on ${{matrix.container }}
    runs-on: self-hosted
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['ubuntu:16.04', 'ubuntu:18.04', 'golang:1.14-buster']

    steps:
      - name: Run Hello World
        run: |
          go version
