name: GitHub ActionsLabs

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master 


jobs:
  build:
    name: GitHub Actions Build Setup
    runs-on: 'self-hosted'
    #runs-on: 'ubuntu-latest'

    steps:
     - name: Checkout code
       uses: actions/checkout@v2

      - name: Test Go Code One
        run: |
          #ls -la ${{ env.WORK_DIRECTORY }}
          ls -la ${{ github.workspace }}
          ls
          pwd

      #- name: Test Go Code One
      #  run: |
      #    go run godemo/hello.go

      #- name: Test Go Code Two
      #  run: |
      #    go run godemo2/hello.go
