name: GitHub Actions Labs

on: push

jobs:
  java-main:
    name: GitHub Actions Build
    runs-on: 'githubactions-agent1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Check Out
        run: |
          ls
