name: Test Branch Name

on: [push]

jobs:
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - name: Extract Branch Name
        shell: bash
        run: |
            echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Display Branch name
        shell: bash
        run: |
          echo "Branch name => ${{ steps.extract_branch.outputs.branch }}"
