name: BUILD-DEMO

on: [push]

env:
  CHECKOUT_BRANCH: ${{ github.event.pull_request.head.ref }}


jobs:
  build:
    name: Base Test
    runs-on: "cicd"
    steps:
      - name: Checkout Repository With Actions 
        uses: actions/checkout@v2
        #with:
        #   ref: ${{ github.event.pull_request.head.ref }}


      - name: Check Workspace
        run: |
          echo "Work Space => ${{ github.workspace }}"
          ls
