name: GitHub Actions Labs

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master 

jobs:
  java-main:
    name: GitHub Actions Build
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Check Out
        run: |
          ls

      - name: Test Go Code
        run: |
          go run godemo/hello.go
