name: Test Branch Name

on: [push]

jobs:
  TestVariables:
    name: Test Environment Variables
    runs-on: ubuntu-latest
    steps:
      - name: Clean Workspace Path
        run: |
           echo "Cleaning Build Workspace"
           rm -Rf ${{ github.workspace }}
           mkdir -p ${{ github.workspace }}

      - name: Checkout Repository With Actions 
        uses: actions/checkout@v2
        with:
           ref: ${{ github.event.pull_request.head.ref }}


      - name: Check Workspace
        run: |
          echo "Work Space => ${{ github.workspace }}"
          ls
            

  Branch_Test:
    name: Test Shell Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Extract Branch Name
        shell: bash
        run: |
            echo "Base Branch => $GITHUB_REF"

      - name: Branch Name
        shell: bash
        run: |
            echo "Branch Name ==> $(git rev-parse --abbrev-ref HEAD)"




  GoCode:
    name: Test Go Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Go Code
        run: |
          go run gocode/main.go
