name: GitHub Actions Labs

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master 

env:
   WORK_DIRECTORY: "go/src"


jobs:
  java-main:
    name: GitHub Actions Build
    runs-on: 'self-hosted'
    #runs-on: 'ubuntu-latest'

    steps:
      - name: Create Directory
        run: |
          mkdir -p ${{ env.WORK_DIRECTORY }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ env.WORK_DIRECTORY }}

      - name: Install Prereqs
        run: |
          sudo apt install -y tree

      - name: Test Go Code One
        run: |
          ls -la ${{ env.WORK_DIRECTORY }}
      #- name: Test Go Code One
      #  run: |
      #    go run ${WORK_DIRECTORY}/godemo/hello.go

      #- name: Test Go Code Two
      #  run: |
      #    go run ${WORK_DIRECTORY}/godemo2/hello.go
