name: Test Branch Name

on: [push]

jobs:
  Branch_Test:
    name: Branch Operations
    runs-on: ubuntu-latest
    steps:
      - name: Extract Branch Name
        shell: bash
        run: |
            echo "Base Branch => $GITHUB_REF"
