name: GitHub ActionsLabs

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master 

env:
   WORK_DIRECTORY: "go/src/github.com/uonyekwuluje/githubactions-recipes"


jobs:
  build:
    name: GitHub Actions Build Setup
    runs-on: 'self-hosted'
    #runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Go Code One
        run: |
          #ls -la ${{ env.WORK_DIRECTORY }}
          ls -la ${{ github.workspace }}
          pwd

      - name: Test Go Code One
        run: |
          go run hello.go
        env:
           GOPATH: /home/runner/work/woodpecker/go
