name: GitHub Actions Labs

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master 

jobs:
  java-main:
    name: GitHub Actions Build
    #runs-on: 'ubuntu-latest'
    runs-on: 'ci'

    steps:
      - name: Create Directory
        run: |
          mkdir -p go/src

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "go/src"

      - name: Test Go Code One
        run: |
          go run go/src/godemo/hello.go

      - name: Test Go Code Two
        run: |
          go run go/src/godemo2/hello.go
