name: BUILD-DEMO

on: 
   push:
      branches:
      - master
   pull_request:
      branches:
      - master

env:
  CHECKOUT_BRANCH: ${{ github.event.pull_request.head.ref }}


jobs:
  bash-build:
    name: Bash Build
    runs-on: "cicd"
    steps:
      - name: Checkout Repository With Actions 
        uses: actions/checkout@v2
        #with:
        #   ref: ${{ github.event.pull_request.head.ref }}

      - name: Shell Test
        run: |
           bash test.sh
        shell: bash {0}

  go-build:
    name: Go Build
    runs-on: "cicd"
    steps:
      - name: Checkout Repository With Actions
        uses: actions/checkout@v2

      - name: Go Version
        run: |
           go version
        shell: bash {0}

      - name: Number Addition
        run: |
           go run gocode/main.go
        shell: bash {0}
