name: GitHub Actions Labs

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master 

env:
   WORK_DIRECTORY: "go/src"


jobs:
  java-main:
    name: GitHub Actions Build
    runs-on: 'ubuntu-latest'

    steps:
      - name: Create Directory
        run: |
          mkdir -p ${WORK_DIRECTORY}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${WORK_DIRECTORY}

      - name: Test Go Code One
        run: |
          go run ${WORK_DIRECTORY}/godemo/hello.go

      - name: Test Go Code Two
        run: |
          go run ${WORK_DIRECTORY}/godemo2/hello.go
